# Generated by Django 6.0.1 on 2026-02-06 08:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_transcript', models.TextField(help_text='Original transcript text')),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_words', models.IntegerField(default=0)),
                ('avg_sentiment', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20, null=True)),
                ('participation_balance', models.FloatField(blank=True, help_text='0-1 score where 1 is perfectly balanced', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.CharField(blank=True, max_length=20, null=True)),
                ('sequence_order', models.IntegerField(help_text='Order in the meeting')),
                ('word_count', models.IntegerField(default=0)),
                ('sentiment_score', models.FloatField(blank=True, help_text='Sentiment from -1 (negative) to 1 (positive)', null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('sentiment_compound', models.FloatField(blank=True, null=True)),
                ('is_question', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='meetings.meeting')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='meetings.speaker')),
            ],
            options={
                'ordering': ['meeting', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages', models.IntegerField(default=0)),
                ('total_words', models.IntegerField(default=0)),
                ('participation_percentage', models.FloatField(default=0.0)),
                ('avg_words_per_message', models.FloatField(default=0.0)),
                ('engagement_score', models.FloatField(default=0.0, help_text='Composite score of involvement (0-100)')),
                ('avg_sentiment', models.FloatField(blank=True, null=True)),
                ('positive_message_count', models.IntegerField(default=0)),
                ('negative_message_count', models.IntegerField(default=0)),
                ('neutral_message_count', models.IntegerField(default=0)),
                ('question_count', models.IntegerField(default=0)),
                ('interruption_count', models.IntegerField(default=0)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='meetings.meeting')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='meetings.speaker')),
            ],
            options={
                'ordering': ['-participation_percentage'],
                'unique_together': {('meeting', 'speaker')},
            },
        ),
    ]
