# Generated by Django 6.0.1 on 2026-02-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingmetrics',
            old_name='negative_message_count',
            new_name='negative_count',
        ),
        migrations.RenameField(
            model_name='meetingmetrics',
            old_name='neutral_message_count',
            new_name='neutral_count',
        ),
        migrations.RenameField(
            model_name='meetingmetrics',
            old_name='positive_message_count',
            new_name='positive_count',
        ),
    ]
